services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    image: poc-shared-publisher:latest
    container_name: poc-shared-publisher
    restart: unless-stopped
    ports:
      - "8080:8080"  # TCP - Sequencer connections
      - "8081:8081"  # HTTP - Metrics and health
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml:ro
    environment:
      - TZ=UTC
