global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'poc-shared-publisher'

scrape_configs:
  # Shared Publisher metrics
  - job_name: 'shared-publisher'
    static_configs:
      - targets: ['shared-publisher:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'shared-publisher'

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
