global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'poc-shared-publisher'
    environment: 'development'

scrape_configs:
  # Shared Publisher metrics
  - job_name: 'shared-publisher'
    static_configs:
      - targets: ['publisher:8081']
    metrics_path: /metrics
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
